# Generated by Django 5.2.6 on 2025-09-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listacontrole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usomodel',
            name='horario_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usomodel',
            name='km_final',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
