# Generated by Django 5.2.6 on 2025-09-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listacontrole', '0002_alter_usomodel_horario_final_alter_usomodel_km_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoristamodel',
            name='empresa',
            field=models.CharField(choices=[('Doptex', 'Doptex'), ('São João Tecelagem', 'Tecelagem'), ('São João Tinturaria', 'Tinturaria'), ('Corradi', 'Corradi'), ('Textil Da Serra', 'Textil')], default='Doptex'),
        ),
        migrations.AlterField(
            model_name='usomodel',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listacontrole.motoristamodel'),
        ),
    ]
