# Generated by Django 5.2.6 on 2025-09-26 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listacontrole', '0003_alter_motoristamodel_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usomodel',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listacontrole.veiculomodels'),
        ),
    ]
