# Generated by Django 5.2.6 on 2025-09-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listacontrole', '0004_alter_usomodel_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usomodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
