# Generated by Django 5.2.6 on 2025-09-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listacontrole', '0005_usomodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usomodel',
            name='status',
        ),
        migrations.AddField(
            model_name='veiculomodels',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
