# Generated by Django 4.2.25 on 2025-10-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listacontrole', '0006_remove_usomodel_status_veiculomodels_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoristamodel',
            name='empresa',
            field=models.CharField(choices=[('Doptex', 'Doptex'), ('São João Tecelagem', 'Tecelagem'), ('São João Tinturaria', 'Tinturaria'), ('Corradi', 'Corradi'), ('Textil Da Serra', 'Textil')], default='Doptex', max_length=50),
        ),
    ]
