# Generated by Django 5.2.8 on 2025-11-14 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listacontrole', '0007_alter_motoristamodel_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usomodel',
            name='km_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AgendamentoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_uso', models.DateField()),
                ('horario_uso', models.TimeField()),
                ('destino', models.CharField()),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listacontrole.motoristamodel')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listacontrole.veiculomodels')),
            ],
        ),
    ]
